import { Skills } from './types';

export const skillInfo: Skills = {
  skillList: [
    {
      skillType: 'Languages',
      skillItems: [
        'Java',
        'Go',
        'SQL',
        'TypeScript',
        'JavaScript',
        'HTML',
        'CSS',
        'C++',
        'Python',
        'C#',
      ],
    },
    {
      skillType: 'Frameworks',
      skillItems: [
        'Spring Boot',
        'Spring MVC',
        'MyBatis',
        'JPA/Hibernate',
        'Quartz',
        'gRPC',
        'Gorm',
        'Gin',
        'Vue',
        'React',
        'Unity',

        // "React-Redux",
        // "Next JS",
        // "Bootstrap",
        // 'Redux-Saga',
        // "Axios",
        // "Sass",
        // "React Native",
      ],
    },
    {
      skillType: 'Tools',
      skillItems: [
        'PostgreSQL',
        'Nginx',
        'Jenkins',
        'Lombok',
        'Redis',
        'Docker',
        'K8s',
        'Kafka',
        'RabbitMQ',
        'Elasticsearch',
        'AWS EC2',
        'SQS',
        'S3',
        'Cloud Watch',
        // "GitHub",
        // "Linux",
        // "Shell",
      ],
    },
  ],
};
